In [53]:
from sqlalchemy import create_engine
import pandas as pd
from data_extraction import *
from binance_keys import api_key,secret_key
from binance.client import Client
from datetime import datetime,timedelta
from functions import *
engine = create_engine('sqlite:///CryptoDB.db')
import warnings
warnings.filterwarnings('ignore')

In [54]:
coin = 'DODOX'
df = pd.read_sql_table(f'{coin}USDT', engine)
df

                        E          s       o       h       l       c
0 2023-08-19 04:47:09.947  DODOXUSDT  0.1001  0.1087  0.0962  0.1006

In [76]:
def get_volatile_dataframe():
    engine = create_engine('sqlite:///CryptoDB.db')

    # Fetch all table names
    inspector = inspect(engine)
    table_names = inspector.get_table_names()

    rows = []

    # Fetch row from each table and append it to rows
    for table in table_names:
        row = pd.read_sql(table, engine)
        try:
            rows.append(row.iloc[0])
        except Exception as e:
            print(f'No data available for {table}')

    # Convert the list of rows into a DataFrame
    df = pd.concat(rows, axis=1).T
    df.reset_index(drop=True , inplace = True)
    
    df['PctRange'] = (df['h'] - df['l']) / abs(df['l']) * 100
    
    df[f'Volatility'] = df['PctRange'].rolling(window=1).mean()
    
    df_volatility = df.sort_values(by='Volatility')
    
    return df_volatility

In [77]:
import pandas as pd
from sqlalchemy import create_engine, inspect

engine = create_engine('sqlite:///CryptoDB.db')

# Fetch all table names
inspector = inspect(engine)
table_names = inspector.get_table_names()

rows = []

# Fetch row from each table and append it to rows
for table in table_names:
    row = pd.read_sql(table, engine)
    try:
        rows.append(row.iloc[0])
    except Exception as e:
        print(f'No data available for {table}')

# Convert the list of rows into a DataFrame
df = pd.concat(rows, axis=1).T
df.reset_index(drop=True)

KeyboardInterrupt:

In [59]:
df_volatility = df.sort_values(by='Volatility')
df_volatility

,E,s,o,h,l,c,PctRange,Volatility
0,2023-08-19 04:45:34.388,USDCUSDT,0.99978,1.0003,0.9996,0.99978,0.070028,0.070028
0,2023-08-19 04:47:02.545,TRXUSDT,0.07209,0.07346,0.07203,0.07345,1.985284,1.985284
0,2023-08-19 04:46:39.043,BTCDOMUSDT,1853.3,1856.4,1818.0,1823.0,2.112211,2.112211
0,2023-08-19 04:46:45.194,IDEXUSDT,0.04289,0.04375,0.04269,0.04359,2.483017,2.483017
0,2023-08-19 04:47:09.788,BNBUSDT,214.39,219.65,214.16,215.56,2.563504,2.563504
...,...,...,...,...,...,...,...,...
0,2023-08-19 04:47:10.964,WLDUSDT,1.3346,1.5859,1.3307,1.4977,19.177876,19.177876
0,2023-08-19 04:47:07.269,UNFIUSDT,3.734,4.55,3.661,3.905,24.282983,24.282983
0,2023-08-19 04:47:11.460,YGGUSDT,0.211,0.2827,0.2104,0.2633,34.363118,34.363118
0,2023-08-19 04:47:10.666,OXTUSDT,0.05054,0.06842,0.0503,0.06756,36.023857,36.023857
0,2023-08-19 04:47:11.280,BLZUSDT,0.08129,0.1183,0.08019,0.10257,47.524629,47.524629

In [60]:
coin = 'BLZ'
df_volatility[df_volatility['s']==f'{coin}USDT']

,E,s,o,h,l,c,PctRange,Volatility
0,2023-08-19 04:47:11.280,BLZUSDT,0.08129,0.1183,0.08019,0.10257,47.524629,47.524629

In [61]:
df_volatility

,E,s,o,h,l,c,PctRange,Volatility
0,2023-08-19 04:45:34.388,USDCUSDT,0.99978,1.0003,0.9996,0.99978,0.070028,0.070028
0,2023-08-19 04:47:02.545,TRXUSDT,0.07209,0.07346,0.07203,0.07345,1.985284,1.985284
0,2023-08-19 04:46:39.043,BTCDOMUSDT,1853.3,1856.4,1818.0,1823.0,2.112211,2.112211
0,2023-08-19 04:46:45.194,IDEXUSDT,0.04289,0.04375,0.04269,0.04359,2.483017,2.483017
0,2023-08-19 04:47:09.788,BNBUSDT,214.39,219.65,214.16,215.56,2.563504,2.563504
...,...,...,...,...,...,...,...,...
0,2023-08-19 04:47:10.964,WLDUSDT,1.3346,1.5859,1.3307,1.4977,19.177876,19.177876
0,2023-08-19 04:47:07.269,UNFIUSDT,3.734,4.55,3.661,3.905,24.282983,24.282983
0,2023-08-19 04:47:11.460,YGGUSDT,0.211,0.2827,0.2104,0.2633,34.363118,34.363118
0,2023-08-19 04:47:10.666,OXTUSDT,0.05054,0.06842,0.0503,0.06756,36.023857,36.023857
0,2023-08-19 04:47:11.280,BLZUSDT,0.08129,0.1183,0.08019,0.10257,47.524629,47.524629

In [62]:
do_not_trade_list = []

In [63]:
selected_coin = df_volatility.iloc[-1]['s']

In [64]:
str_date = (datetime.now()- timedelta(days=3)).strftime('%b %d,%Y')
end_str = datetime.now().strftime('%b %d,%Y')
str_date,end_str

('Aug 16,2023', 'Aug 19,2023')

In [65]:
str_date = (datetime.now()- timedelta(days=6)).strftime('%b %d,%Y')
end_str = (datetime.now() +  timedelta(days=3)).strftime('%b %d,%Y')
timeframe ='1h'
client=Client(api_key,secret_key)
df=dataextract(coin,str_date,end_str,timeframe,client)

               OpenTime     open     high      low    close        volume  \
0   2023-08-12 19:00:00  0.06189  0.06199  0.06047  0.06092  1.526095e+08
1   2023-08-12 20:00:00  0.06094  0.07076  0.06094  0.06852  5.477847e+08
2   2023-08-12 21:00:00  0.06852  0.07567  0.06748  0.07307  1.058207e+09
3   2023-08-12 22:00:00  0.07308  0.07387  0.07136  0.07272  3.787023e+08
4   2023-08-12 23:00:00  0.07273  0.07600  0.07162  0.07207  4.391861e+08
..                  ...      ...      ...      ...      ...           ...
146 2023-08-18 21:00:00  0.10799  0.10803  0.09910  0.10105  5.212152e+08
147 2023-08-18 22:00:00  0.10108  0.10394  0.10006  0.10231  1.445134e+08
148 2023-08-18 23:00:00  0.10231  0.10329  0.10123  0.10169  1.083234e+08
149 2023-08-19 00:00:00  0.10170  0.10214  0.09951  0.09965  1.268337e+08
150 2023-08-19 01:00:00  0.09964  0.10116  0.09955  0.10060  2.982305e+07

                  CloseTime  BLZ-QuoteAssetVolume  BLZ-NumberOfTrades  \
0   2023-08-12 19:59:59.999          9.317365e+06             34044.0
1   2023-08-12 20:59:59.999          3.633863e+07            155066.0
2   2023-08-12 21:59:59.999          7.635742e+07            268261.0
3   2023-08-12 22:59:59.999          2.744408e+07             94151.0
4   2023-08-12 23:59:59.999          3.201065e+07            109680.0
..                      ...                   ...                 ...
146 2023-08-18 21:59:59.999          5.322138e+07            202041.0
147 2023-08-18 22:59:59.999          1.479096e+07             73068.0
148 2023-08-18 23:59:59.999          1.109122e+07             58794.0
149 2023-08-19 00:59:59.999          1.276575e+07             61834.0
150 2023-08-19 01:59:59.999          2.998674e+06             13161.0

       BLZ-TBBAV     BLZ-TBQAV  BLZ-ignore  hour  minute  day  month  year
0     78109756.0  4.768989e+06         0.0    19       0   12      8  2023
1    312990916.0  2.072203e+07         0.0    20       0   12      8  2023
2    550011535.0  3.970466e+07         0.0    21       0   12      8  2023
3    196365617.0  1.422987e+07         0.0    22       0   12      8  2023
4    225196072.0  1.643185e+07         0.0    23       0   12      8  2023
..           ...           ...         ...   ...     ...  ...    ...   ...
146  256125578.0  2.613460e+07         0.0    21       0   18      8  2023
147   76823445.0  7.860942e+06         0.0    22       0   18      8  2023
148   54011805.0  5.532212e+06         0.0    23       0   18      8  2023
149   62099600.0  6.253398e+06         0.0     0       0   19      8  2023
150   17570995.0  1.766646e+06         0.0     1       0   19      8  2023

[151 rows x 17 columns]
Gathering BLZ_1h.csv

    dataextract(coin,str_date,end_str,timeframe,client)
    supertrend(coin)  #getting details about current one is important, max,min values
    4.41 not reached? get in trade : select another coin,update do not trade list
    in_trade ? set_tp,keep on check for tp hit, trend_change ? update_dntradelist : pass : select another coin,

In [66]:
df

,OpenTime,hour,minute,day,month,year,open,high,low,close,volume
0,2023-08-12 19:00:00,19,0,12,8,2023,0.06189,0.06199,0.06047,0.06092,1.526095e+08
1,2023-08-12 20:00:00,20,0,12,8,2023,0.06094,0.07076,0.06094,0.06852,5.477847e+08
2,2023-08-12 21:00:00,21,0,12,8,2023,0.06852,0.07567,0.06748,0.07307,1.058207e+09
3,2023-08-12 22:00:00,22,0,12,8,2023,0.07308,0.07387,0.07136,0.07272,3.787023e+08
4,2023-08-12 23:00:00,23,0,12,8,2023,0.07273,0.07600,0.07162,0.07207,4.391861e+08
...,...,...,...,...,...,...,...,...,...,...,...
146,2023-08-18 21:00:00,21,0,18,8,2023,0.10799,0.10803,0.09910,0.10105,5.212152e+08
147,2023-08-18 22:00:00,22,0,18,8,2023,0.10108,0.10394,0.10006,0.10231,1.445134e+08
148,2023-08-18 23:00:00,23,0,18,8,2023,0.10231,0.10329,0.10123,0.10169,1.083234e+08
149,2023-08-19 00:00:00,0,0,19,8,2023,0.10170,0.10214,0.09951,0.09965,1.268337e+08
150,2023-08-19 01:00:00,1,0,19,8,2023,0.09964,0.10116,0.09955,0.10060,2.982305e+07

In [67]:
period = 14
atr1 = 1
super_df=supertrend(coin,df, period,atr1)

In [68]:
super_df[['OpenTime','close','in_uptrend']]

               OpenTime    close  in_uptrend
0   2023-08-12 19:00:00  0.06092        True
1   2023-08-12 20:00:00  0.06852        True
2   2023-08-12 21:00:00  0.07307        True
3   2023-08-12 22:00:00  0.07272        True
4   2023-08-12 23:00:00  0.07207        True
..                  ...      ...         ...
146 2023-08-18 21:00:00  0.10105       False
147 2023-08-18 22:00:00  0.10231       False
148 2023-08-18 23:00:00  0.10169       False
149 2023-08-19 00:00:00  0.09965       False
150 2023-08-19 01:00:00  0.10060       False

[151 rows x 3 columns]

In [69]:
def calculate_min_max(x):
    if x['signal'] == 'Buy':
        return (((x['local_max'] - x['entry'])/x['entry']),
                (x['entry'] - x['local_min'])/x['entry'])
    else:
        return ((x['entry'] - x['local_min'])/x['entry'],
               ( x['local_max'] - x['entry'])/x['entry'])

In [70]:
trade_df=create_signal_df(super_df,df,coin,timeframe,atr1,period,100,100)

In [71]:
trade_df

,signal,entry,tp,trade,close_price,TradeOpenTime,percentage,OpenTime,hour,minute,...,local_min_bar,upper_band,lower_band,max_log_return,min_log_return,prev_max_log_return,prev_min_log_return,prev_local_max_bar,prev_local_min_bar,prev_percentage
2,Sell,0.09482,-9.38718,L,0.11342,2023-08-14 04:00:00,-0.196161,2023-08-14 03:00:00,3,0,...,0.0,0.106053,0.092387,0.008226,0.218097,0.131292,0.063622,6.0,2.0,-0.015880
3,Buy,0.11342,11.45542,L,0.10284,2023-08-14 06:00:00,-0.093282,2023-08-14 05:00:00,5,0,...,1.0,0.117635,0.102295,0.049198,0.131017,0.008226,0.218097,2.0,0.0,-0.196161
4,Sell,0.10284,-10.18116,W,0.08412,2023-08-14 08:00:00,0.182030,2023-08-14 07:00:00,7,0,...,24.0,0.117619,0.099941,0.235998,0.037340,0.049198,0.131017,1.0,1.0,-0.093282
5,Buy,0.08412,8.49612,L,0.08042,2023-08-15 10:00:00,-0.043985,2023-08-15 09:00:00,9,0,...,4.0,0.087389,0.080451,0.017000,0.062292,0.235998,0.037340,0.0,24.0,0.182030
6,Sell,0.08042,-7.96158,L,0.08475,2023-08-15 16:00:00,-0.053842,2023-08-15 15:00:00,15,0,...,2.0,0.083074,0.077176,0.027108,0.067894,0.017000,0.062292,0.0,4.0,-0.043985
7,Buy,0.08475,8.55975,W,0.09995,2023-08-15 22:00:00,0.179351,2023-08-15 21:00:00,21,0,...,0.0,0.086311,0.080329,0.292035,0.012507,0.027108,0.067894,6.0,2.0,-0.053842
8,Sell,0.09995,-9.89505,L,0.10112,2023-08-16 08:00:00,-0.011706,2023-08-16 07:00:00,7,0,...,8.0,0.107153,0.096477,0.056928,0.100550,0.292035,0.012507,8.0,0.0,0.179351
9,Buy,0.10112,10.21312,L,0.09322,2023-08-16 19:00:00,-0.078125,2023-08-16 18:00:00,18,0,...,0.0,0.107246,0.096814,0.001088,0.118572,0.056928,0.100550,10.0,8.0,-0.011706
10,Sell,0.09322,-9.22878,W,0.09108,2023-08-16 20:00:00,0.022956,2023-08-16 19:00:00,19,0,...,16.0,0.100989,0.089371,0.098906,0.069406,0.001088,0.118572,0.0,0.0,-0.078125
11,Buy,0.09108,9.19908,L,0.08670,2023-08-17 14:00:00,-0.048090,2023-08-17 13:00:00,13,0,...,2.0,0.092584,0.087066,0.036451,0.110233,0.098906,0.069406,3.0,16.0,0.022956
12,Sell,0.08670,-8.58330,L,0.09212,2023-08-17 18:00:00,-0.062514,2023-08-17 17:00:00,17,0,...,7.0,0.088985,0.081525,0.075087,0.091811,0.036451,0.110233,2.0,2.0,-0.048090
13,Buy,0.09212,9.30412,W,0.10479,2023-08-18 11:00:00,0.137538,2023-08-18 10:00:00,10,0,...,0.0,0.091074,0.084246,0.284195,0.013786,0.075087,0.091811,17.0,7.0,-0.062514
14,Sell,0.10479,-10.37421,W,0.00000,2023-08-18 18:00:00,1.000000,2023-08-18 17:00:00,17,0,...,4.0,0.112975,0.100205,0.054299,0.060979,0.284195,0.013786,1.0,0.0,0.137538

In [72]:
trade_df.columns

Index(['signal', 'entry', 'tp', 'trade', 'close_price', 'TradeOpenTime',
       'percentage', 'OpenTime', 'hour', 'minute', 'day', 'month', 'size',
       'ma_7', 'ma_25', 'ma_99', 'ma_100', 'ma_200', 'ema_100', 'ema_200',
       'ema_55', 'ema_5', 'ema_10', 'ema_20', 'ema_33', 'rsi', 'macd',
       'macdsignal', 'macdhist', 'slowk', 'slowd', 'candle_count', 'local_max',
       'local_min', 'local_max_bar', 'local_min_bar', 'upper_band',
       'lower_band', 'max_log_return', 'min_log_return', 'prev_max_log_return',
       'prev_min_log_return', 'prev_local_max_bar', 'prev_local_min_bar',
       'prev_percentage'],
      dtype='object')

In [73]:
trade_df[['signal', 'entry', 'tp', 'trade', 'close_price', 'TradeOpenTime',
       'rsi','slowk','percentage','max_log_return', 'min_log_return','local_max',
       'local_min']]

,signal,entry,tp,trade,close_price,TradeOpenTime,rsi,slowk,percentage,max_log_return,min_log_return,local_max,local_min
2,Sell,0.09482,-9.38718,L,0.11342,2023-08-14 04:00:00,57.026978,58.760105,-0.196161,0.008226,0.218097,0.11550,0.09404
3,Buy,0.11342,11.45542,L,0.10284,2023-08-14 06:00:00,70.029291,58.734101,-0.093282,0.049198,0.131017,0.11900,0.09856
4,Sell,0.10284,-10.18116,W,0.08412,2023-08-14 08:00:00,56.908707,73.817814,0.182030,0.235998,0.037340,0.10668,0.07857
5,Buy,0.08412,8.49612,L,0.08042,2023-08-15 10:00:00,43.582492,49.462840,-0.043985,0.017000,0.062292,0.08555,0.07888
6,Sell,0.08042,-7.96158,L,0.08475,2023-08-15 16:00:00,37.898176,23.601132,-0.053842,0.027108,0.067894,0.08588,0.07824
7,Buy,0.08475,8.55975,W,0.09995,2023-08-15 22:00:00,52.111389,61.008961,0.179351,0.292035,0.012507,0.10950,0.08369
8,Sell,0.09995,-9.89505,L,0.10112,2023-08-16 08:00:00,63.557943,61.753388,-0.011706,0.056928,0.100550,0.11000,0.09426
9,Buy,0.10112,10.21312,L,0.09322,2023-08-16 19:00:00,59.848008,34.795284,-0.078125,0.001088,0.118572,0.10123,0.08913
10,Sell,0.09322,-9.22878,W,0.09108,2023-08-16 20:00:00,45.763305,34.105565,0.022956,0.098906,0.069406,0.09969,0.08400
11,Buy,0.09108,9.19908,L,0.08670,2023-08-17 14:00:00,50.483896,66.152963,-0.048090,0.036451,0.110233,0.09440,0.08104
12,Sell,0.08670,-8.58330,L,0.09212,2023-08-17 18:00:00,41.887074,58.834046,-0.062514,0.075087,0.091811,0.09466,0.08019
13,Buy,0.09212,9.30412,W,0.10479,2023-08-18 11:00:00,64.186007,35.937394,0.137538,0.284195,0.013786,0.11830,0.09085
14,Sell,0.10479,-10.37421,W,0.00000,2023-08-18 18:00:00,64.438030,35.470439,1.000000,0.054299,0.060979,0.11118,0.09910

In [74]:
(0.001211 - 0.000808)/0.001211

0.3327828241123039

In [75]:
 np.log(0.001211) - np.log(0.000808)

0.4046396850319969